### ISSUE TITLE
Error from batch_norm

### ISSUE THREAD

**Issue by akaraspt** [paarthneekhara/text-to-image#13]
I got this error when I was trying to run your scripts.

```
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 76, in main
    input_tensors, variables, loss, outputs, checks = gan.build_model()
  File "/home/akara/Workspace/text-to-image/model.py", line 44, in build_model
    disc_wrong_image, disc_wrong_image_logits   = self.discriminator(t_wrong_image, t_real_caption, reuse = True)
  File "/home/akara/Workspace/text-to-image/model.py", line 165, in discriminator
    h1 = ops.lrelu( self.d_bn1(ops.conv2d(h0, self.options['df_dim']*2, name = 'd_h1_conv'))) #16
  File "/home/akara/Workspace/text-to-image/Utils/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/akara/miniconda2/envs/gan/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_bn1/d_bn1_2/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

It was when the script is trying to create another discriminator.

```
disc_real_image, disc_real_image_logits   = self.discriminator(t_real_image, t_real_caption)
disc_wrong_image, disc_wrong_image_logits   = self.discriminator(t_wrong_image, t_real_caption, reuse = True) # Here
disc_fake_image, disc_fake_image_logits   = self.discriminator(fake_image, t_real_caption, reuse = True)
```

I printed all variables but it seems to initialize with different variable names, but the `reuse = True`.

**Comment by csbkwang** [comment]
same problem

**Comment by jiang2764** [comment]
Is there any solution for this issue?  @csbkwang @akaraspt @paarthneekhara

**Comment by paarthneekhara** [comment]
What tensorflow version are you using? IIRC the code ran on version r0.10. I don't have access to a machine to debug the code right now.

**Comment by jiang2764** [comment]
I used tensorflow 1.0. Thanks Paarth @paarthneekhara

**Comment by paarthneekhara** [comment]
So did it work?

**Comment by jiang2764** [comment]
I got the same error when i want to run the train code. That's why I asked you and others. Thanks. @paarthneekhara

**Comment by paarthneekhara** [comment]
Hi, This is a compatibility issue with the tf update. Replace the batch_norm class code in ops.py by the one written here https://github.com/iamaaditya/DCGAN-tensorflow/blob/master/ops.py . This should fix the issue.

**Comment by Duke-Wyh** [comment]
I actually add the ops.py to replace the batch_norm.However, it still exists another problem:
Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
How can I do to solve the problem?Thanks!

**Comment by Duke-Wyh** [comment]
At last I solved the problem!
There were two ways that we need to solve it.First, we should add the ops.py.Second,we should add with tf.variable_scope(tf.get_variable_scope())
to our code.
Thanks everyone!

**Comment by OwalnutO** [comment]
I also got stuck in this problem and solve it in another way. My tensorflow version is '0.12.1'. I replace the batch_norm class code in ops.py. with code below:

class batch_norm(object):
    """Code modification of http://stackoverflow.com/a/33950177"""
    def __init__(self, epsilon=1e-5, momentum = 0.1, name="batch_norm"):
        with tf.variable_scope(name) as scope:
            self.epsilon = epsilon
            self.momentum = momentum
            #self.batch_size = batch_size

            self.ema = tf.train.ExponentialMovingAverage(decay=self.momentum)
            self.name=name

    def __call__(self, x, train=True):
        shape = x.get_shape().as_list()

        with tf.variable_scope(self.name) as scope:
            self.gamma = tf.get_variable("gamma", [shape[-1]],
                                initializer=tf.random_normal_initializer(1., 0.02))
            self.beta = tf.get_variable("beta", [shape[-1]],
                                initializer=tf.constant_initializer(0.))

            self.mean, self.variance = tf.nn.moments(x, [0, 1, 2])

            return tf.nn.batch_norm_with_global_normalization(
                x, self.mean, self.variance, self.beta, self.gamma, self.epsilon,
                scale_after_normalization=True)
   It is copied and modified from https://github.com/Hanock/generating_images_part_by_part/blob/master/code/lib/ops.py

**Comment by OwalnutO** [comment]
I also got stuck in this problem and solve it in another way. My tensorflow version is '0.12.1'. I replace the batch_norm class code in ops.py. with code below:

class batch_norm(object):
    """Code modification of http://stackoverflow.com/a/33950177"""
    def __init__(self, epsilon=1e-5, momentum = 0.1, name="batch_norm"):
        with tf.variable_scope(name) as scope:
            self.epsilon = epsilon
            self.momentum = momentum
            #self.batch_size = batch_size

            self.ema = tf.train.ExponentialMovingAverage(decay=self.momentum)
            self.name=name

    def __call__(self, x, train=True):
        shape = x.get_shape().as_list()

        with tf.variable_scope(self.name) as scope:
            self.gamma = tf.get_variable("gamma", [shape[-1]],
                                initializer=tf.random_normal_initializer(1., 0.02))
            self.beta = tf.get_variable("beta", [shape[-1]],
                                initializer=tf.constant_initializer(0.))

            self.mean, self.variance = tf.nn.moments(x, [0, 1, 2])

            return tf.nn.batch_norm_with_global_normalization(
                x, self.mean, self.variance, self.beta, self.gamma, self.epsilon,
                scale_after_normalization=True)
        

It is copied and modified from https://github.com/Hanock/generating_images_part_by_part/blob/master/code/lib/ops.py

**Comment by zhhezhhe** [comment]
@Duke-Wyh thanks, but  where to put tf.variable_scope(tf.get_variable_scope())?

**Comment by zhhezhhe** [comment]
@jiang2764 Did you solve this problem? I have the same problem. I used tensorflow 1.0.1.

**Comment by jiang2764** [comment]
@zhhezhhe Please follow @paarthneekhara 's suggestion, update the ops file, and then modify the argument format for function tf.nn.sigmoid_cross_entropy_with_logits. The training process should work. Thanks @paarthneekhara ! I am running the training process now. I stopped working on this after I asked the question. Now it is time to go for this.

**Comment by paarthneekhara** [comment]
@OwalnutO , @jiang2764 if the method worked for you, can you please submit a pull request with the patch for the same?

**Comment by Peri044** [comment]
@paarthneekhara @jiang2764 @zhhezhhe 
I updated the ops file and modified the arguments. I still face the issue  Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope? 
I use Tensorflow 1.1. Any help is appreciated. Thanks.

**Comment by zhhezhhe** [comment]
this may help you https://github.com/YearnyeenHo/text-to-image  .


在 2017年7月5日，上午1:39，Dheeraj Peri <notifications@github.com> 写道：

@paarthneekhara <https://github.com/paarthneekhara> @jiang2764
<https://github.com/jiang2764> @zhhezhhe <https://github.com/zhhezhhe>
I updated the ops file and modified the arguments. I still face the issue
Variable d_h0_conv/w/Adam/ does not exist, or was not created with
tf.get_variable(). Did you mean to set reuse=None in VarScope?
I use Tensorflow 1.1. Any help is appreciated. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/paarthneekhara/text-to-image/issues/13#issuecomment-312924850>,
or mute the thread

**Comment by zhhezhhe** [comment]
this may help you https://github.com/YearnyeenHo/text-to-image  . YearnyeenHo fixed the batch_norm issue for tensorflow 1.0在 2017年7月5日，上午1:39，Dheeraj Peri <notifications@github.com> 写道：@paarthneekhara @jiang2764 @zhhezhhe
I updated the ops file and modified the arguments. I still face the issue  Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
I use Tensorflow 1.1. Any help is appreciated. Thanks.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/paarthneekhara/text-to-image","title":"paarthneekhara/text-to-image","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/paarthneekhara/text-to-image" class="">https://github.com/paarthneekhara/text-to-image</a>" class=""><a href="https://github.com/paarthneekhara/text-to-image" class="">https://github.com/paarthneekhara/text-to-image</a></a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Peri044 in #13: @paarthneekhara @jiang2764 @zhhezhhe \r\nI updated the ops file and modified the arguments. I still face the issue  Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope? \r\nI use Tensorflow 1.1. Any help is appreciated. Thanks. "}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/paarthneekhara/text-to-image/issues/13#issuecomment-312924850" class="">https://github.com/paarthneekhara/text-to-image/issues/13#issuecomment-312924850</a>" class=""><a href="https://github.com/paarthneekhara/text-to-image/issues/13#issuecomment-312924850" class="">https://github.com/paarthneekhara/text-to-image/issues/13#issuecomment-312924850</a></a>"}}}

**Comment by SpadesQ** [comment]
where to put tf.variable_scope(tf.get_variable_scope())? @Duke-Wyh 

Using https://github.com/YearnyeenHo/text-to-image, I still have this problem in tensorflow1.3.
Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope? 
How to solve?
Thank you@ zhhezhhe

**Comment by 314rated** [comment]
Hi @SpadesQ , were you able to find a solution to this? I am facing the same issue.

On replacing ops file, problem with Adam comes while training.
If trying to use checkpoint, otFoundError (see above for traceback): Tensor name "d_bn1/moving_mean" not found in checkpoint files Data/Models/latest_model_flowers_temp.ckpt

**Comment by ravindra82** [comment]
@paarthneekhara 

When i try to generate images using the pre trained model, Even i get the following error.

NotFoundError (see above for traceback): Tensor name "d_bn1/moving_mean" not found in checkpoint files Data/Models/latest_model_flowers_temp.ckpt

I am using the code from here https://github.com/YearnyeenHo/text-to-image and have the downloaded the checkpoint file from the link given.

Please suggest a solution.

**Comment by TheScott463** [comment]
@paarthneekhara Thanks for writing this code. I have the same problem as above. I'm running the latest release of each lib needed, but this one stumped me. Is there a good solution that makes this work? All the dialog above is a bit hodgepodge. I'd like to see your solution please.
